import { emptyDocument, type ExtractedDocument, type FieldConfidence } from "./schema";

/**
 * Reading an Indian tax invoice out of plain text, without a model.
 *
 * This is what makes the free path worth having: a PDF generated by the
 * vendor's own accounting software carries its text intact, and the fields
 * that matter on a GST invoice are unusually well-signposted — a GSTIN has a
 * checksum-shaped 15-character format that nothing else in the document
 * matches, "Invoice No." precedes the number, and the grand total is the
 * largest currency figure on the page. Getting those five or six fields right
 * turns the review screen from data entry into checking.
 *
 * It does not attempt line items: a table's columns are lost the moment a PDF
 * is flattened to text, and a wrong line is worse than a blank one. Those come
 * from the model path, or from the reviewer.
 */

/** 2 state digits, 10 PAN characters, entity code, 'Z', checksum. */
const GSTIN = /\b\d{2}[A-Z]{5}\d{4}[A-Z][0-9A-Z]Z[0-9A-Z]\b/;
const PAN = /\b[A-Z]{5}\d{4}[A-Z]\b/;
const EMAIL = /\b[\w.%+-]+@[\w.-]+\.[A-Za-z]{2,}\b/;
const PHONE = /(?:\+91[\s-]?)?\b[6-9]\d{9}\b/;

/** State code → state name, for deriving place of supply from a GSTIN. */
const GST_STATE_CODES: Record<string, string> = {
  "01": "Jammu and Kashmir", "02": "Himachal Pradesh", "03": "Punjab",
  "04": "Chandigarh", "05": "Uttarakhand", "06": "Haryana", "07": "Delhi",
  "08": "Rajasthan", "09": "Uttar Pradesh", "10": "Bihar", "11": "Sikkim",
  "12": "Arunachal Pradesh", "13": "Nagaland", "14": "Manipur", "15": "Mizoram",
  "16": "Tripura", "17": "Meghalaya", "18": "Assam", "19": "West Bengal",
  "20": "Jharkhand", "21": "Odisha", "22": "Chhattisgarh", "23": "Madhya Pradesh",
  "24": "Gujarat", "26": "Dadra and Nagar Haveli and Daman and Diu",
  "27": "Maharashtra", "29": "Karnataka", "30": "Goa", "31": "Lakshadweep",
  "32": "Kerala", "33": "Tamil Nadu", "34": "Puducherry", "35": "Andaman and Nicobar Islands",
  "36": "Telangana", "37": "Andhra Pradesh", "38": "Ladakh", "97": "Other Territory",
};

export function stateFromGstin(gstin: string | null | undefined): string | null {
  if (!gstin || gstin.length < 2) return null;
  return GST_STATE_CODES[gstin.slice(0, 2)] ?? null;
}

/** "1,23,456.78" / "₹ 1234" / "(1234.00)" → 1234.78 style numbers. */
function toAmount(raw: string): number | null {
  const cleaned = raw.replace(/[₹,\s]/g, "").replace(/[()]/g, "");
  const value = Number(cleaned);
  return Number.isFinite(value) ? value : null;
}

/** dd/mm/yyyy, dd-mm-yy, 3 Apr 2026, 2026-04-03 → ISO date, or null. */
export function parseIndianDate(raw: string | null | undefined): string | null {
  if (!raw) return null;
  const text = raw.trim();

  const iso = text.match(/\b(\d{4})-(\d{2})-(\d{2})\b/);
  if (iso) return `${iso[1]}-${iso[2]}-${iso[3]}`;

  const numeric = text.match(/\b(\d{1,2})[/.-](\d{1,2})[/.-](\d{2,4})\b/);
  if (numeric) {
    const day = numeric[1].padStart(2, "0");
    const month = numeric[2].padStart(2, "0");
    let year = numeric[3];
    if (year.length === 2) year = Number(year) > 70 ? `19${year}` : `20${year}`;
    if (Number(month) >= 1 && Number(month) <= 12 && Number(day) >= 1 && Number(day) <= 31) {
      return `${year}-${month}-${day}`;
    }
  }

  const months = ["jan", "feb", "mar", "apr", "may", "jun", "jul", "aug", "sep", "oct", "nov", "dec"];
  const worded = text
    .toLowerCase()
    .match(/\b(\d{1,2})[\s-]*(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*[\s,-]*(\d{2,4})\b/);
  if (worded) {
    const day = worded[1].padStart(2, "0");
    const month = String(months.indexOf(worded[2]) + 1).padStart(2, "0");
    let year = worded[3];
    if (year.length === 2) year = `20${year}`;
    return `${year}-${month}-${day}`;
  }
  return null;
}

/**
 * The amount that follows a tax label on its own line, e.g. "CGST 9%: 1,530.00"
 * or "CGST 9%: 1530". The rate itself ("9%") is stripped out of the snippet
 * first so a whole-number amount is never mistaken for the percentage that
 * precedes it.
 */
function taxAmountAfterLabel(text: string, label: RegExp): number | null {
  const hit = text.match(label);
  if (hit?.index === undefined) return null;
  const line = text.slice(hit.index + hit[0].length).split("\n")[0].slice(0, 40);
  const withoutRate = line.replace(/\d+(?:\.\d+)?\s*%/g, "");
  const amount = withoutRate.match(/([\d,]+(?:\.\d{1,2})?)/);
  return amount ? toAmount(amount[1]) : null;
}

/** First capture group of the first pattern that hits. */
function firstMatch(text: string, patterns: RegExp[]): string | null {
  for (const pattern of patterns) {
    const hit = text.match(pattern);
    if (hit?.[1]) return hit[1].trim();
  }
  return null;
}

export interface HeuristicReading {
  document: ExtractedDocument;
  confidence: FieldConfidence;
}

export function readInvoiceText(
  text: string,
  context: { ownGstin?: string | null; ownName?: string | null } = {}
): HeuristicReading {
  const document = emptyDocument();
  const confidence: FieldConfidence = {};
  const compact = text.replace(/\r/g, "");
  const upper = compact.toUpperCase();

  // Every GSTIN on the page; ours identifies which side of the deal we are on,
  // so the other one belongs to the party.
  const gstins = [...compact.matchAll(new RegExp(GSTIN.source, "g"))].map((m) => m[0]);
  const own = context.ownGstin?.toUpperCase();
  const partyGstin = gstins.find((g) => g !== own) ?? null;
  if (partyGstin) {
    document.partyGstin = partyGstin;
    document.partyState = stateFromGstin(partyGstin);
    confidence.partyGstin = 0.95;
  }

  // Which way the document points. Our own GSTIN under "bill to" means the
  // goods came to us; under "seller" it means we issued it.
  if (own && gstins.includes(own)) {
    const ownIndex = compact.toUpperCase().indexOf(own);
    const billToIndex = upper.search(/BILL\s*TO|BUYER|CONSIGNEE|SHIP\s*TO/);
    document.direction =
      billToIndex >= 0 && ownIndex > billToIndex ? "INCOMING" : "OUTGOING";
    document.docType = document.direction === "INCOMING" ? "PURCHASE_BILL" : "SALES_INVOICE";
    confidence.direction = 0.6;
  } else if (gstins.length > 0) {
    // Without the organization's own GSTIN configured there is no way to tell
    // which side of the deal it is on — this is a coin flip, not a reading,
    // and has to be scored low enough that the review screen flags it rather
    // than a reviewer trusting a confidently-labelled wrong guess.
    document.direction = "INCOMING";
    document.docType = "PURCHASE_BILL";
    confidence.direction = context.ownGstin ? 0.4 : 0.15;
  }

  const pan = compact.match(PAN)?.[0] ?? null;
  if (pan && pan !== partyGstin?.slice(2, 12)) document.partyPan = pan;

  // "Invoice No.: STC/2026/0417", "Bill # 4417", "Invoice Number - A/22".
  // The punctuation between label and value varies per printing package, so
  // any run of it is allowed rather than exactly one character.
  document.documentNumber = firstMatch(compact, [
    /(?:invoice|bill|voucher|challan)\s*(?:no|number|#)[.:#\s-]*([A-Za-z0-9/\\_-]{2,32})/i,
    /\binv[.:#\s-]+([A-Za-z0-9/\\_-]{2,32})/i,
  ]);
  if (document.documentNumber) confidence.documentNumber = 0.75;

  const dateText = firstMatch(compact, [
    /(?:invoice|bill|voucher)\s*date\s*[:.\-]?\s*([0-9A-Za-z/,. -]{6,20})/i,
    /\bdated?\s*[:.\-]?\s*([0-9A-Za-z/,. -]{6,20})/i,
  ]);
  document.documentDate = parseIndianDate(dateText);
  if (document.documentDate) confidence.documentDate = 0.7;

  const dueText = firstMatch(compact, [
    /due\s*date\s*[:.\-]?\s*([0-9A-Za-z/,. -]{6,20})/i,
  ]);
  document.dueDate = parseIndianDate(dueText);

  // "P.O." has to be followed by a label word or a separator, or every address
  // line containing "Point" hands back a purchase order number.
  document.poNumber = firstMatch(compact, [
    /\b(?:p\.?\s?o\.?|purchase\s*order)\s*(?:no|number|#)[.:#\s-]*([A-Za-z0-9/\\_-]{2,32})/i,
    /\bp\.?\s?o\.?\s*[:#-]\s*([A-Za-z0-9/\\_-]{2,32})/i,
  ]);

  const amountOf = (patterns: RegExp[]): number | null => {
    const raw = firstMatch(compact, patterns);
    return raw ? toAmount(raw) : null;
  };

  document.totalAmount = amountOf([
    /(?:grand\s*total|total\s*(?:invoice\s*)?(?:amount|value)|amount\s*payable|net\s*payable)\s*[:.\-]?\s*(?:₹|rs\.?|inr)?\s*([\d,]+\.?\d{0,2})/i,
  ]);
  if (document.totalAmount != null) confidence.totalAmount = 0.7;

  document.subtotal = amountOf([
    /(?:taxable\s*(?:value|amount)|sub\s*-?\s*total|amount\s*before\s*tax)\s*[:.\-]?\s*(?:₹|rs\.?|inr)?\s*([\d,]+\.?\d{0,2})/i,
  ]);
  // A tax line usually carries its rate before its amount — "CGST 9%: 1,530.00",
  // but a hand-typed one may print the amount as a whole number — "CGST 9%: 1530".
  // Stripping the "9%" out of the line before hunting for a number means the
  // rate itself never gets mistaken for the amount.
  document.cgstAmount = taxAmountAfterLabel(compact, /\bcgst\b/i);
  document.sgstAmount = taxAmountAfterLabel(compact, /\bs?gst\b/i);
  document.igstAmount = taxAmountAfterLabel(compact, /\bigst\b/i);
  document.roundOff = amountOf([/round(?:ed)?\s*off\s*[:.\-]?\s*\(?(-?[\d,]+\.?\d{0,2})\)?/i]);

  if (/reverse\s*charge\s*[:\-]?\s*(yes|applicable|y\b)/i.test(compact)) {
    document.reverseCharge = true;
  }

  document.placeOfSupply =
    firstMatch(compact, [/place\s*of\s*supply\s*[:.\-]?\s*([A-Za-z ]{3,40})/i]) ??
    document.partyState ??
    null;

  document.partyEmail = compact.match(EMAIL)?.[0] ?? null;
  document.partyPhone = compact.match(PHONE)?.[0] ?? null;

  // The supplier's name is nearly always the largest line at the top; take the
  // first substantial line that is not a heading. A header block of labelled
  // fields — "Bill Date: 12 Dec 2021", "Invoice No: 12345" — often sits beside
  // or above the name in the original layout and survives OCR in that order,
  // so a "Label: value" shaped line is excluded outright rather than treated
  // as a candidate: a business name is never written that way.
  const headLines = compact
    .split("\n")
    .map((line) => line.trim())
    .filter(Boolean)
    .slice(0, 12);
  const nameLine = headLines.find(
    (line) =>
      line.length >= 4 &&
      line.length <= 70 &&
      !/^(tax\s*)?invoice|^bill of|^gstin|^original|^duplicate|^credit note|^debit note/i.test(line) &&
      !/^[A-Za-z][A-Za-z ]{1,25}:\s*\S/.test(line) &&
      !GSTIN.test(line) &&
      /[A-Za-z]{3}/.test(line)
  );
  if (nameLine && nameLine.toLowerCase() !== context.ownName?.toLowerCase()) {
    document.partyName = nameLine;
    confidence.partyName = 0.45;
  }

  const asserted = Object.values(confidence).filter((v): v is number => typeof v === "number");
  confidence.overall = asserted.length
    ? asserted.reduce((a, b) => a + b, 0) / asserted.length
    : 0;

  return { document, confidence };
}
