import { NextRequest, NextResponse } from "next/server";
import { auth } from "@/lib/auth/config";
import { prisma } from "@/lib/prisma";
import { cookies } from "next/headers";
import QRCode from "qrcode";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

/**
 * E-Invoice Generation API
 *
 * In production, this would integrate with:
 * - NIC (National Informatics Centre) e-Invoice portal
 * - GST Suvidha Providers (GSPs)
 *
 * This implementation generates:
 * - IRN (Invoice Reference Number) - simulated
 * - QR Code with invoice data
 * - Signed invoice JSON
 */

interface EInvoiceData {
  Version: string;
  TranDtls: {
    TaxSch: string;
    SupTyp: string;
    RegRev: string;
    IgstOnIntra: string;
  };
  DocDtls: {
    Typ: string;
    No: string;
    Dt: string;
  };
  SellerDtls: {
    Gstin: string;
    LglNm: string;
    TrdNm: string;
    Addr1: string;
    Loc: string;
    Pin: string;
    Stcd: string;
  };
  BuyerDtls: {
    Gstin: string;
    LglNm: string;
    TrdNm: string;
    Addr1: string;
    Loc: string;
    Pin: string;
    Stcd: string;
    Pos: string;
  };
  ItemList: Array<{
    SlNo: string;
    PrdDesc: string;
    IsServc: string;
    HsnCd: string;
    Qty: number;
    Unit: string;
    UnitPrice: number;
    TotAmt: number;
    Discount: number;
    AssAmt: number;
    GstRt: number;
    IgstAmt: number;
    CgstAmt: number;
    SgstAmt: number;
    TotItemVal: number;
  }>;
  ValDtls: {
    AssVal: number;
    IgstVal: number;
    CgstVal: number;
    SgstVal: number;
    Discount: number;
    OthChrg: number;
    TotInvVal: number;
    TotInvValFc?: number;
  };
}

// State codes for India
const STATE_CODES: Record<string, string> = {
  "Andhra Pradesh": "37",
  "Arunachal Pradesh": "12",
  "Assam": "18",
  "Bihar": "10",
  "Chhattisgarh": "22",
  "Goa": "30",
  "Gujarat": "24",
  "Haryana": "06",
  "Himachal Pradesh": "02",
  "Jharkhand": "20",
  "Karnataka": "29",
  "Kerala": "32",
  "Madhya Pradesh": "23",
  "Maharashtra": "27",
  "Manipur": "14",
  "Meghalaya": "17",
  "Mizoram": "15",
  "Nagaland": "13",
  "Odisha": "21",
  "Punjab": "03",
  "Rajasthan": "08",
  "Sikkim": "11",
  "Tamil Nadu": "33",
  "Telangana": "36",
  "Tripura": "16",
  "Uttar Pradesh": "09",
  "Uttarakhand": "05",
  "West Bengal": "19",
  "Delhi": "07",
};

function getStateCode(state: string | null): string {
  if (!state) return "27"; // Default Maharashtra
  return STATE_CODES[state] || "27";
}

function generateIRN(invoiceNumber: string, sellerGstin: string, fiscalYear: string): string {
  // In production, IRN is generated by NIC
  // This is a simulation: SHA-256 hash of invoice details
  const data = `${sellerGstin}|${invoiceNumber}|${fiscalYear}`;
  // Simple hash simulation
  let hash = 0;
  for (let i = 0; i < data.length; i++) {
    const char = data.charCodeAt(i);
    hash = ((hash << 5) - hash) + char;
    hash = hash & hash;
  }
  const hashStr = Math.abs(hash).toString(16).padStart(16, '0');
  return `${hashStr}${Date.now().toString(16)}`.substring(0, 64).toUpperCase();
}

export async function GET(
  request: NextRequest,
  { params }: { params: Promise<{ orgId: string; invoiceId: string }> }
) {
  try {
    await cookies();
    const session = await auth();
    const { orgId, invoiceId } = await params;

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const orgUser = await prisma.organizationUser.findUnique({
      where: {
        organizationId_userId: {
          organizationId: orgId,
          userId: session.user.id,
        },
      },
    });

    if (!orgUser) {
      return NextResponse.json({ error: "Access denied" }, { status: 403 });
    }

    // Get invoice with e-invoice details
    const invoice = await prisma.invoice.findFirst({
      where: { id: invoiceId, organizationId: orgId },
      select: {
        id: true,
        invoiceNumber: true,
        irnNumber: true,
        qrCode: true,
        eInvoiceStatus: true,
        date: true,
        totalAmount: true,
      },
    });

    if (!invoice) {
      return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
    }

    return NextResponse.json({
      invoiceId: invoice.id,
      invoiceNumber: invoice.invoiceNumber,
      irnNumber: invoice.irnNumber,
      qrCode: invoice.qrCode,
      eInvoiceStatus: invoice.eInvoiceStatus,
      date: invoice.date,
      totalAmount: Number(invoice.totalAmount),
    });
  } catch (error) {
    console.error("Error fetching e-invoice:", error);
    return NextResponse.json({ error: "Failed to fetch e-invoice" }, { status: 500 });
  }
}

export async function POST(
  request: NextRequest,
  { params }: { params: Promise<{ orgId: string; invoiceId: string }> }
) {
  try {
    await cookies();
    const session = await auth();
    const { orgId, invoiceId } = await params;

    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const orgUser = await prisma.organizationUser.findUnique({
      where: {
        organizationId_userId: {
          organizationId: orgId,
          userId: session.user.id,
        },
      },
    });

    if (!orgUser) {
      return NextResponse.json({ error: "Access denied" }, { status: 403 });
    }

    const body = await request.json();
    const { action = "generate" } = body;

    // Get invoice with all details
    const invoice = await prisma.invoice.findFirst({
      where: { id: invoiceId, organizationId: orgId },
      include: {
        organization: true,
        party: true,
        items: {
          include: {
            item: true,
            tax: true,
          },
        },
        taxes: {
          include: {
            tax: true,
          },
        },
      },
    });

    if (!invoice) {
      return NextResponse.json({ error: "Invoice not found" }, { status: 404 });
    }

    if (action === "generate") {
      // Check if already generated
      if (invoice.irnNumber && invoice.eInvoiceStatus === "GENERATED") {
        return NextResponse.json({
          error: "E-invoice already generated",
          irnNumber: invoice.irnNumber,
        }, { status: 400 });
      }

      // Validate required fields
      if (!invoice.organization.gstNo) {
        return NextResponse.json({ error: "Seller GSTIN required" }, { status: 400 });
      }

      // Build e-invoice JSON
      const fiscalYear = invoice.date.getMonth() >= 3
        ? `${invoice.date.getFullYear()}-${invoice.date.getFullYear() + 1}`
        : `${invoice.date.getFullYear() - 1}-${invoice.date.getFullYear()}`;

      const sellerStateCode = getStateCode(invoice.organization.state);
      const buyerStateCode = invoice.party.gstNo
        ? invoice.party.gstNo.substring(0, 2)
        : getStateCode(invoice.party.billingState);

      const isInterState = sellerStateCode !== buyerStateCode;

      // Calculate tax totals
      let igstTotal = 0;
      let cgstTotal = 0;
      let sgstTotal = 0;

      const itemList = invoice.items.map((item, index) => {
        const taxRate = item.tax ? Number(item.tax.rate) : 0;
        const taxableAmount = Number(item.taxableAmount);
        const taxAmount = Number(item.taxAmount);

        let igst = 0, cgst = 0, sgst = 0;
        if (isInterState) {
          igst = taxAmount;
          igstTotal += igst;
        } else {
          cgst = taxAmount / 2;
          sgst = taxAmount / 2;
          cgstTotal += cgst;
          sgstTotal += sgst;
        }

        return {
          SlNo: String(index + 1),
          PrdDesc: item.description,
          IsServc: item.item?.type === "SERVICES" ? "Y" : "N",
          HsnCd: item.hsnCode || item.item?.hsnCode || "",
          Qty: Number(item.quantity),
          Unit: "NOS",
          UnitPrice: Number(item.unitPrice),
          TotAmt: Number(item.quantity) * Number(item.unitPrice),
          Discount: Number(item.discountAmount),
          AssAmt: taxableAmount,
          GstRt: taxRate,
          IgstAmt: igst,
          CgstAmt: cgst,
          SgstAmt: sgst,
          TotItemVal: taxableAmount + taxAmount,
        };
      });

      const eInvoiceData: EInvoiceData = {
        Version: "1.1",
        TranDtls: {
          TaxSch: "GST",
          SupTyp: "B2B",
          RegRev: "N",
          IgstOnIntra: "N",
        },
        DocDtls: {
          Typ: invoice.type === "CREDIT_NOTE" ? "CRN" : invoice.type === "DEBIT_NOTE" ? "DBN" : "INV",
          No: invoice.invoiceNumber,
          Dt: invoice.date.toISOString().split("T")[0].split("-").reverse().join("/"),
        },
        SellerDtls: {
          Gstin: invoice.organization.gstNo,
          LglNm: invoice.organization.legalName || invoice.organization.name,
          TrdNm: invoice.organization.name,
          Addr1: invoice.organization.address || "",
          Loc: invoice.organization.city || "",
          Pin: invoice.organization.postalCode || "",
          Stcd: sellerStateCode,
        },
        BuyerDtls: {
          Gstin: invoice.party.gstNo || "URP",
          LglNm: invoice.party.name,
          TrdNm: invoice.party.name,
          Addr1: invoice.party.billingAddress || "",
          Loc: invoice.party.billingCity || "",
          Pin: invoice.party.billingPostal || "",
          Stcd: buyerStateCode,
          Pos: buyerStateCode,
        },
        ItemList: itemList,
        ValDtls: {
          AssVal: Number(invoice.subtotal),
          IgstVal: igstTotal,
          CgstVal: cgstTotal,
          SgstVal: sgstTotal,
          Discount: Number(invoice.discountAmount),
          OthChrg: 0,
          TotInvVal: Number(invoice.totalAmount),
        },
      };

      // Generate IRN
      const irnNumber = generateIRN(
        invoice.invoiceNumber,
        invoice.organization.gstNo,
        fiscalYear
      );

      // Generate QR code
      const qrData = JSON.stringify({
        SellerGstin: eInvoiceData.SellerDtls.Gstin,
        BuyerGstin: eInvoiceData.BuyerDtls.Gstin,
        DocNo: eInvoiceData.DocDtls.No,
        DocTyp: eInvoiceData.DocDtls.Typ,
        DocDt: eInvoiceData.DocDtls.Dt,
        TotInvVal: eInvoiceData.ValDtls.TotInvVal,
        ItemCnt: itemList.length,
        Irn: irnNumber,
      });

      const qrCodeDataUrl = await QRCode.toDataURL(qrData, {
        width: 200,
        margin: 2,
        errorCorrectionLevel: "M",
      });

      // Update invoice with e-invoice details
      const updatedInvoice = await prisma.invoice.update({
        where: { id: invoiceId },
        data: {
          irnNumber,
          qrCode: qrCodeDataUrl,
          eInvoiceStatus: "GENERATED",
        },
      });

      // Log audit
      await prisma.auditLog.create({
        data: {
          organizationId: orgId,
          userId: session.user.id,
          action: "CREATE",
          entityType: "E_INVOICE",
          entityId: invoiceId,
          newData: {
            irnNumber,
            invoiceNumber: invoice.invoiceNumber,
            totalAmount: Number(invoice.totalAmount),
          },
        },
      });

      return NextResponse.json({
        success: true,
        irnNumber,
        qrCode: qrCodeDataUrl,
        eInvoiceStatus: "GENERATED",
        eInvoiceData,
        message: "E-invoice generated successfully",
      });
    }

    if (action === "cancel") {
      if (!invoice.irnNumber || invoice.eInvoiceStatus !== "GENERATED") {
        return NextResponse.json({ error: "No e-invoice to cancel" }, { status: 400 });
      }

      const { reason } = body;
      if (!reason) {
        return NextResponse.json({ error: "Cancellation reason required" }, { status: 400 });
      }

      // In production, this would call NIC API to cancel
      await prisma.invoice.update({
        where: { id: invoiceId },
        data: {
          eInvoiceStatus: "CANCELLED",
        },
      });

      // Log audit
      await prisma.auditLog.create({
        data: {
          organizationId: orgId,
          userId: session.user.id,
          action: "UPDATE",
          entityType: "E_INVOICE",
          entityId: invoiceId,
          oldData: { eInvoiceStatus: "GENERATED" },
          newData: { eInvoiceStatus: "CANCELLED", reason },
        },
      });

      return NextResponse.json({
        success: true,
        eInvoiceStatus: "CANCELLED",
        message: "E-invoice cancelled successfully",
      });
    }

    return NextResponse.json({ error: "Invalid action" }, { status: 400 });
  } catch (error) {
    console.error("Error processing e-invoice:", error);
    return NextResponse.json({ error: "Failed to process e-invoice" }, { status: 500 });
  }
}
